import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@/auth';
import prisma from '@/lib/db';
import { generateAutoDashboard, analyzeSchema } from '@/lib/auto-dashboard';
import { isGroqConfigured } from '@/lib/groq';

// POST /api/ai/auto-dashboard - Génère un dashboard automatique
export async function POST(req: NextRequest) {
  try {
    const session = await auth();
    if (!session?.user) {
      return NextResponse.json({ error: 'Non autorisé' }, { status: 401 });
    }

    if (!isGroqConfigured()) {
      return NextResponse.json({
        error: 'Groq API non configurée',
        hint: 'Définissez GROQ_API_KEY. Obtenez une clé gratuite sur https://console.groq.com/'
      }, { status: 500 });
    }

    const body = await req.json();
    const { data, context, workspaceId, saveAs } = body;

    if (!data || !Array.isArray(data) || data.length === 0) {
      return NextResponse.json({ error: 'Données invalides' }, { status: 400 });
    }

    console.log(`[AutoDashboard] Génération pour ${data.length} lignes...`);

    const dashboardConfig = await generateAutoDashboard({
      data,
      context: context || 'Analyse générale des données',
    });

    let savedDashboard = null;
    if (saveAs && workspaceId) {
      try {
        savedDashboard = await prisma.dashboard.create({
          data: {
            name: saveAs || dashboardConfig.title,
            description: dashboardConfig.description,
            workspaceId,
            sourceType: 'csv',
            config: {
              autoGenerated: true,
              generatedAt: new Date().toISOString(),
              ...dashboardConfig,
            } as any,
          },
        });

        await prisma.auditLog.create({
          data: {
            workspaceId,
            userId: (session.user as any).id,
            action: 'AUTO_DASHBOARD_CREATE',
            entityType: 'Dashboard',
            entityId: savedDashboard.id,
            metaJson: { name: savedDashboard.name, kpiCount: dashboardConfig.kpis.length } as any,
          },
        });
      } catch (saveError) {
        console.error('[AutoDashboard] Erreur sauvegarde:', saveError);
      }
    }

    return NextResponse.json({
      success: true,
      config: dashboardConfig,
      dashboard: savedDashboard,
      meta: {
        rowCount: data.length,
        columnCount: Object.keys(data[0] || {}).length,
        kpiCount: dashboardConfig.kpis.length,
        chartCount: dashboardConfig.charts.length,
      },
    });
  } catch (error: any) {
    console.error('[AutoDashboard] Erreur:', error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

// GET /api/ai/auto-dashboard?dashboardId=xxx
export async function GET(req: NextRequest) {
  try {
    const session = await auth();
    if (!session?.user) {
      return NextResponse.json({ error: 'Non autorisé' }, { status: 401 });
    }

    const { searchParams } = new URL(req.url);
    const dashboardId = searchParams.get('dashboardId');

    if (!dashboardId) {
      return NextResponse.json({ error: 'dashboardId requis' }, { status: 400 });
    }

    const dashboard = await prisma.dashboard.findUnique({
      where: { id: dashboardId },
      include: {
        workspace: {
          include: {
            memberships: { where: { userId: (session.user as any).id } },
          },
        },
      },
    });

    if (!dashboard || !dashboard.workspace?.memberships?.length) {
      return NextResponse.json({ error: 'Dashboard non trouvé' }, { status: 404 });
    }

    const config = dashboard.config as any;
    return NextResponse.json({ success: true, config: { title: dashboard.name, ...config } });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
